-- C:\Program Files (x86)\H2\bin>java -jar h2-2.3.232.jar
-- jdbc:h2:tcp://localhost/~/test

drop table if exists member CASCADE;
create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);